### ISSUE TITLE
Can't switch between multiple windows in the same app

### ISSUE THREAD

**Issue by codycodes** [JuanmaMenendez/AutoHotkey-script-Open-Show-Apps#1]
Hello! This is sort of a feature/bug fix request. I'd like to be able to switch between windows of the same application (e.g. between chrome windows) using the assigned keyboard shortcut. I wonder if there's a way to switch between individual windows in this script?

I'd also like to be able to only switch to windows on the current desktop, and understand this might be more difficult. I'm really enjoying it so far. I might take a crack at it if I figure out how to do those things in autohotkey. But wanted to bring it to your attention as an issue if you have any ideas :D.

**Comment by JuanmaMenendez** [comment]
Hello @codycodes, thanks for your suggestion.

I added to the [main script](https://github.com/JuanmaMenendez/AutoHotkey-script-Open-Show-Apps/releases/latest/download/AutoHotkey-script-Open-Show-Apps.ahk) the hotkey Alt + ` (key above Tab key) to switch between multiple open windows in the same app as you requested.

I will not work at the moment in the "desktop distinction" feature, maybe in the future, I will. If you do it before, feel free to create a Pull Request.

I hope the new feature be useful for you ;)
