### ISSUE TITLE
Request to provide support to activate the previous window of the same application

### ISSUE THREAD

**Issue by gayashanbc** [JuanmaMenendez/AutoHotkey-script-Open-Show-Apps#11]
Hi @JuanmaMenendez,

Your scripts are really useful and thanks a lot for providing them.
I would really like to see the support to activate the previous window of the same application if possible.

Cheers,
Gayashan

**Comment by zdanek** [comment]
#12 resolves this, I've checked it and approved so maybe @JuanmaMenendez would merge it :)
