### ISSUE TITLE
Always opens new instance of Windows store Calculator app

### ISSUE THREAD

**Issue by nujabse** [JuanmaMenendez/AutoHotkey-script-Open-Show-Apps#9]
I tried to use this script to open or switch to Windows store Calculator app. The default config in the script file says 
```
; F9 - Open||Show "Windows store Calculator app"
F9:: OpenOrShowAppBasedOnAppModelUserID("Calculator", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App")
```
However, when I run the script, pressing `F9` will always call a new instance of the Calculator app. If I press `F9` 3 times, I will get three new Calculator windows instead of switching to existent Calculator app window. The other traditional windows apps, however, doesn't suffer from this problem. Can this be fixed?

**Comment by serpro69** [comment]
Maybe this will help someone. Had the same issue with another app. In my case the reason was that application name (title) was dynamic based on the contents/state of the app. See if the app has an option for a static window title.

**Comment by JuanmaMenendez** [comment]
Fixed in https://github.com/JuanmaMenendez/AutoHotkey-script-Open-Show-Apps/pull/12
